### ISSUE TITLE
Small typo in PostgreSQL section

### ISSUE THREAD

**Issue by DarkSkull91** [chacka0101/Kali_Linux_Certified_Professional#1]
Hi, 
thanks for this incredible cheatsheet. I noticed that there is a small typo in PostgreSQL section at this line:
`root@chacka0101:/# cat /etc/postgresql/11/main/postgresql.conf | more (Archivo de configuración del SSH)`
This line should be:
`root@chacka0101:/# cat /etc/postgresql/11/main/postgresql.conf | more (Archivo de configuración del PostgreSQL)`

**Comment by chacka0101** [comment]
Perfect!

@DarkSkull91 Thanks for the contribution!
