### ISSUE TITLE
Missing -b parameter?

### ISSUE THREAD

**Issue by DarkSkull91** [chacka0101/Kali_Linux_Certified_Professional#2]
Hi chacka0101, because I'm studying the Advanced Usage chapther on the book, I'm pretty sure that the answer to the 103rd question:
_Which of the following commands will generate a binary package from and unsigned source package with unsigned .buildinfo and .changes file?
`dpkg-buildpackage -us -uc`_

is:
`dpkg-buildpackage -us -uc -b`

What do you think?

**Comment by chacka0101** [comment]
![2024-09-20_185700](https://github.com/user-attachments/assets/3c60e92e-871b-439e-9498-7fe86b1df7da)

Yes Sr. elementary my dear @DarkSkull91 

Thx!

**Comment by lxndrblz** [comment]
Funny enough it is none of the listed options in their practice quiz:

<img width="692" height="170" alt="Image" src="https://github.com/user-attachments/assets/fae0de01-dbe1-4f49-be4c-74824f7a743a" />

**Comment by chacka0101** [comment]
Hahaha, you're right, it must have worked at some point.
